apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: immigration-ingress
  namespace: immigration-support-system

spec:
  ingressClassName: nginx

  rules:
    - host: immigration.local

      http:
        paths:
          - path: /api
            pathType: Prefix

            backend:
              service:
                name: api-gateway

                port:
                  number: 8080

          - path: /
            pathType: Prefix

            backend:
              service:
                name: frontend

                port:
                  number: 80
