apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: immigration-support-system

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend
        version: "1.0"

    spec:
      containers:
        - name: frontend
          image: rrsec5/frontend:1.0
          imagePullPolicy: IfNotPresent

          resources:
            requests:
              cpu: 50m
              memory: 64Mi

            limits:
              cpu: 200m
              memory: 256Mi

          ports:
            - containerPort: 80
