apiVersion: apps/v1
kind: Deployment

metadata:
  name: mysql
  namespace: immigration-support-system

spec:
  replicas: 1

  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql

    spec:
      containers:
        - name: mysql
          image: mysql:8.0

          resources:
            requests:
              cpu: 500m
              memory: 512Mi

            limits:
              cpu: 1
              memory: 1Gi

          ports:
            - containerPort: 3306

          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immigration-support-system-secret
                  key: MYSQL_ROOT_PASSWORD

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immigration-support-system-secret
                  key: DB_PASSWORD

            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: immigration-support-system-config
                  key: DB_USER

            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: immigration-support-system-config
                  key: DB_NAME

          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql

            - name: mysql-init-script
              mountPath: /docker-entrypoint-initdb.d

      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc

        - name: mysql-init-script
          configMap:
            name: mysql-init-script
