apiVersion: v1
kind: Secret

metadata:
  name: immigration-support-system-secret
  namespace: immigration-support-system

type: Opaque

stringData:
  DB_PASSWORD: app_password

  MYSQL_ROOT_PASSWORD: root_password

  JWT_SECRET: ABC123ABC123ABC123ABC123ABC123ABC123ABC123ABC123ABC123ABC123ABC1
