apiVersion: apps/v1
kind: Deployment

metadata:
  name: user-service
  namespace: immigration-support-system

spec:
  replicas: 1

  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
        version: "1.2"

    spec:
      containers:
        - name: user-service
          image: rrsec5/user-service:1.2
          imagePullPolicy: IfNotPresent

          resources:
            requests:
              cpu: 100m
              memory: 256Mi

            limits:
              cpu: 2000m
              memory: 2Gi

          ports:
            - containerPort: 8081

          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: immigration-support-system-config
                  key: DB_URL

            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: immigration-support-system-config
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immigration-support-system-secret
                  key: DB_PASSWORD

            - name: EUREKA_URL
              valueFrom:
                configMapKeyRef:
                  name: immigration-support-system-config
                  key: EUREKA_URL

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: immigration-support-system-secret
                  key: JWT_SECRET

            - name: JWT_EXPIRATION
              valueFrom:
                configMapKeyRef:
                  name: immigration-support-system-config
                  key: JWT_EXPIRATION

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081

            initialDelaySeconds: 40
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081

            initialDelaySeconds: 60
            periodSeconds: 20
