apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-gateway
  namespace: immigration-support-system

spec:
  replicas: 1

  selector:
    matchLabels:
      app: api-gateway

  template:
    metadata:
      labels:
        app: api-gateway
        version: "1.2"

    spec:
      containers:
        - name: api-gateway
          image: rrsec5/api-gateway:1.2
          imagePullPolicy: IfNotPresent

          resources:
            requests:
              cpu: 250m
              memory: 512Mi

            limits:
              cpu: 500m
              memory: 1Gi

          ports:
            - containerPort: 8080

          env:
            - name: EUREKA_URL
              valueFrom:
                configMapKeyRef:
                  name: immigration-support-system-config
                  key: EUREKA_URL

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080

            initialDelaySeconds: 40
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080

            initialDelaySeconds: 60
            periodSeconds: 20
