apiVersion: apps/v1
kind: Deployment

metadata:
  name: country-service
  namespace: immigration-support-system

spec:
  replicas: 1

  selector:
    matchLabels:
      app: country-service

  template:
    metadata:
      labels:
        app: country-service
        version: "1.1"

    spec:
      containers:
        - name: country-service
          image: rrsec5/country-service:1.1
          imagePullPolicy: IfNotPresent

          resources:
            requests:
              cpu: 100m
              memory: 256Mi

            limits:
              cpu: 2000m
              memory: 2Gi

          ports:
            - containerPort: 8082

          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: immigration-support-system-config
                  key: DB_URL

            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: immigration-support-system-config
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immigration-support-system-secret
                  key: DB_PASSWORD

            - name: EUREKA_URL
              valueFrom:
                configMapKeyRef:
                  name: immigration-support-system-config
                  key: EUREKA_URL

          startupProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082

            initialDelaySeconds: 20
            failureThreshold: 12
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082

            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082

            initialDelaySeconds: 60
            periodSeconds: 20
