apiVersion: v1
kind: Service

metadata:
  name: country-service
  namespace: immigration-support-system

spec:
  selector:
    app: country-service

  ports:
    - port: 8082
      targetPort: 8082

  type: ClusterIP
