apiVersion: v1
kind: Service

metadata:
  name: recommendation-service
  namespace: immigration-support-system

spec:
  selector:
    app: recommendation-service

  ports:
    - port: 8083
      targetPort: 8083

  type: ClusterIP
