spring.application.name=api-gateway

server.port=8080

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.server.webflux.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

# Routes
spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/users/**,/api/auth/**,/api/languages/**,/api/professions/**,/api/financial-levels/**


spring.cloud.gateway.server.webflux.routes[1].id=country-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://COUNTRY-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/countries/**,/api/reviews/**

spring.cloud.gateway.server.webflux.routes[2].id=recommendation-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://RECOMMENDATION-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/recommendations/**

management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true

management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
