{{- if .Values.services.recommendationService.enabled }}

{{ include "immigration-system.service" 
(dict 
"name" "recommendation-service"
"config" .Values.services.recommendationService
"root" .
) }}

{{- end }}