apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "immigration-system.name" . }}-config
  namespace: {{ .Values.namespace }}

  labels:
    {{- include "immigration-system.labels" . | nindent 4 }}

data:

  DB_NAME: {{ .Values.config.dbName | quote }}

  DB_USER: {{ .Values.config.dbUser | quote }}

  DB_URL: {{ .Values.config.dbUrl | quote }}

  MYSQL_HOST: {{ .Values.config.mysqlHost | quote }}

  MYSQL_PORT: {{ .Values.config.mysqlPort | quote }}

  EUREKA_URL: {{ .Values.config.eurekaUrl | quote }}

  SPRING_PROFILES_ACTIVE: {{ .Values.config.springProfile | quote }}

  JWT_EXPIRATION: {{ .Values.config.jwtExpiration | quote }}